name: 'Bug report'
description: 'Help me improve the project by creating a report.'
labels: ["bug"]
assignees:
    - 'rrk567301'
body:
    -
        type: checkboxes
        attributes:
            label: 'Prerequisites'
            description: 'By submitting this issue, you agree to the following:'
            options:
                -
                    label: 'I confirm that I have reviewed existing open and closed issues to ensure this is not a duplicate.'
                    required: true
    -
        type: textarea
        attributes:
            label: 'What happened?'
            description: 'Also tell me, what did you expect to happen?'
            placeholder: 'A clear and concise description of the bug.'
        validations:
            required: true
    -
        type: textarea
        attributes:
            label: 'Steps to reproduce'
            placeholder: |
                1. Go to '...'
                2. Click on '...'
                3. Scroll down to '...'
                4. See error
        validations:
            required: true
    -
        type: textarea
        attributes:
            label: 'Relevant log output'
            description: 'This will be automatically formatted into code, so no need for backticks.'
            render: 'shell'
    -
        type: textarea
        attributes:
            label: 'Additional context'
            description: 'Additional information that may help me resolve the issue.'
            placeholder: '[e.g. Operating System]'
